### ISSUE TITLE
break into several smaller modules

### ISSUE THREAD

**Issue by fr1ll** [fr1ll/clip-plot#11]

**Comment by CarloOtano** [comment]
Not sure where `get_atlas_data()` should go.  Do we place in with web_config or images module?

**Comment by fr1ll** [comment]
Good question. 🤔

The images module handles jpgs, so I favor putting it there. Also, atlases are akin to thumbnails, and that's in images or should be.

Sound okay?

**Comment by CarloOtano** [comment]
I want to change the function name of `get_atlas_data`.  Function either gets atlas directory or creates atlas. Either way it always returns the atlas directory. It does not get or load any actual atlas data.  

I am thinking `create_atlas`.  What do you think?

**Comment by fr1ll** [comment]
Yes, agree. `create_atlas` is more clear.

**Comment by fr1ll** [comment]
Done throughout (too many commits to list)
